name: 0.3.$(rev:rrr)

trigger:
- master

schedules:
- cron: 0 5 * * 6
  branches:
    include:
    - master
  always: true

strategy:
  matrix:
    linux:
      imageName: "ubuntu-latest"
      solutionName: "EndlessClient.Linux.sln"
      platform: "Linux"
      dropDir: net6.0
    windows:
      imageName: "windows-latest"
      solutionName: "EndlessClient.sln"
      platform: "Windows"
      dropDir: net6.0-windows

pool:
  vmImage: $(imageName)

variables:
  buildConfiguration: Release

steps:
- checkout: self
  persistCredentials: true
- task: UseDotNet@2
  displayName: 'Install .Net core 3.1.x runtime'
  inputs:
    packageType: runtime
    version: 3.1.x
- task: UseDotNet@2
  displayName: 'Install .Net 6 runtime/sdk'
  inputs:
    version: 6.0.x

- task: DotNetCoreCLI@2
  displayName: 'dotnet restore'
  inputs:
    command: 'restore'
    verbosityRestore: 'minimal'
    projects: '$(Build.SourcesDirectory)\$(solutionName)'
- task: DotNetCoreCLI@2
  displayName: 'dotnet build'
  inputs:
    command: 'build'
    projects: '$(Build.SourcesDirectory)\$(solutionName)'
    arguments: '--configuration $(buildConfiguration)'
- task: DotNetCoreCLI@2
  displayName: 'dotnet test - skipping EOLib.Graphics.Test (not supported on VSTS agent)'
  inputs:
    command: 'test'
    projects: '$(Build.SourcesDirectory)\$(solutionName)'
    arguments: '--filter "TestCategory!=GraphicsDevice" --configuration $(buildConfiguration)'

- task: ArchiveFiles@2
  displayName: 'ZIP EndlessClient'
  inputs:
    rootFolderOrFile: $(Build.SourcesDirectory)\bin\$(buildConfiguration)\client\$(dropDir)\
    archiveFile: $(Build.ArtifactStagingDirectory)\EndlessClient.$(platform).zip
- task: ArchiveFiles@2
  displayName: 'ZIP EOBot'
  inputs:
    rootFolderOrFile: $(Build.SourcesDirectory)\bin\$(buildConfiguration)\utils\EOBot\net6.0\
    archiveFile: $(Build.ArtifactStagingDirectory)\EOBot.$(platform).zip

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifacts'
  inputs:
    PathtoPublish: $(Build.ArtifactStagingDirectory)
    ArtifactName: EndlessClient

- script: |
    git tag build/$(Build.BuildNumber)
    git push origin build/$(Build.BuildNumber)
  workingDirectory:  $(Build.SourcesDirectory)
  displayName: Tag sources on CI/Manual builds
  condition: and(succeeded(), or(eq(variables['build.reason'], 'IndividualCI'), eq(variables['build.reason'], 'Manual')))
