name: 0.3.$(rev:rrr)

trigger:
- master

schedules:
- cron: 0 5 * * 6
  branches:
    include:
    - master
  always: true

strategy:
  matrix:
    # TODO: enable build for linux
    # linux:
    #   imageName: "ubuntu-latest"
    windows:
      imageName: "windows-latest"

pool:
  vmImage: $(imageName)

variables:
  buildConfiguration: 'Release'

steps:
- checkout: self
  persistCredentials: true
- task: UseDotNet@2
  displayName: 'Install .Net core 3.1.x runtime'
  inputs:
    packageType: runtime
    version: 3.1.x
- task: UseDotNet@2
  displayName: 'Install .Net 6 runtime/sdk'
  inputs:
    version: 6.0.x
- task: DotNetCoreCLI@2
  displayName: 'dotnet restore'
  inputs:
    command: 'restore'
    verbosityRestore: 'minimal'
    projects: '$(Build.SourcesDirectory)\EndlessClient.sln'
- task: DotNetCoreCLI@2
  displayName: 'dotnet build'
  inputs:
    command: 'build'
    projects: '$(Build.SourcesDirectory)\EndlessClient.sln'
- task: DotNetCoreCLI@2
  displayName: 'dotnet test - skipping EOLib.Graphics.Test (not supported on VSTS agent)'
  inputs:
    command: 'test'
    projects: '$(Build.SourcesDirectory)\EndlessClient.sln'
    arguments: '--filter="TestCategory!=GraphicsDevice'
- task: CopyFiles@2
  displayName: 'Copy Files to EndlessClient drop upload directory'
  inputs:
    SourceFolder: $(Build.SourcesDirectory)\bin\$(buildConfiguration)\net6.0-windows\
    Contents: '**'
    TargetFolder: $(Build.ArtifactStagingDirectory)\EndlessClient
- task: CopyFiles@2
  displayName: 'Copy Files to EOBot drop upload directory'
  inputs:
    SourceFolder: $(Build.SourcesDirectory)\bin\$(buildConfiguration)\utils\EOBot\net6.0\
    Contents: '**'
    TargetFolder: $(Build.ArtifactStagingDirectory)\EOBot
- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: EndlessClient'
  inputs:
    PathtoPublish: $(Build.ArtifactStagingDirectory)\EndlessClient
    ArtifactName: EndlessClient
    TargetPath: '$(Build.DefinitionName)\$(Build.BuildNumber)'
- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: EOBot'
  inputs:
    PathtoPublish: $(Build.ArtifactStagingDirectory)\EOBot
    ArtifactName: EOBot
    TargetPath: '$(Build.DefinitionName)\$(Build.BuildNumber)'
- script: |
    git tag build/$(Build.BuildNumber)
    git push origin build/$(Build.BuildNumber)
  workingDirectory:  $(Build.SourcesDirectory)
  displayName: Tag sources on CI/Manual builds
  condition: or(eq(variables['build.reason'], 'IndividualCI'), eq(variables['build.reason'], 'Manual'))
