name: 0.4.$(rev:rrr)

trigger:
- master

schedules:
- cron: 0 5 * * 6
  branches:
    include:
    - master
  always: true

strategy:
  matrix:
    linux:
      imageName: "ubuntu-latest"
      solutionName: "EndlessClient.Linux.sln"
      friendlyPlatform: "Linux"
      dropDir: net6.0
    windows:
      imageName: "windows-latest"
      solutionName: "EndlessClient.sln"
      friendlyPlatform: "Windows"
      dropDir: net6.0-windows

pool:
  vmImage: $(imageName)

variables:
  buildConfiguration: Release

steps:
- checkout: self
  persistCredentials: true
- task: UseDotNet@2
  displayName: 'Install .Net core 3.1.x runtime'
  inputs:
    packageType: runtime
    version: 3.1.x
- task: UseDotNet@2
  displayName: 'Install .Net 6 runtime/sdk'
  inputs:
    version: 6.0.x
- task: Assembly-Info-NetCore@3
  inputs:
    Path: '$(Build.SourcesDirectory)'
    FileNames: '**/EOLib*!(Test).csproj'
    InsertAttributes: true
    FileEncoding: 'auto'
    WriteBOM: false
    GenerateDocumentationFile: 'true'
    GeneratePackageOnBuild: 'true'
    PackageRequireLicenseAcceptance: 'false'
    Authors: 'Ethan Moffat'
    Copyright: 'Copyright © 2014-2022 Ethan Moffat'
    PackageLicenseExpression: 'MIT'
    PackageProjectUrl: 'https://github.com/ethanmoffat/EndlessClient'
    RepositoryUrl: 'https://github.com/ethanmoffat/EndlessClient'
    RepositoryType: 'git'
    PackageTags: 'endless-online eo'
    VersionNumber: '$(Build.BuildNumber)'
    FileVersionNumber: '$(Build.BuildNumber)'
    InformationalVersion: '$(Build.BuildNumber)'
    PackageVersion: '$(Build.BuildNumber)'
    LogLevel: 'verbose'
    FailOnWarning: false
    DisableTelemetry: false
- task: DotNetCoreCLI@2
  displayName: 'dotnet restore'
  inputs:
    command: 'restore'
    verbosityRestore: 'minimal'
    projects: '$(Build.SourcesDirectory)/$(solutionName)'
- script: |
    echo ttf-mscorefonts-installer msttcorefonts/accepted-mscorefonts-eula select true | sudo debconf-set-selections
    sudo apt-get install -y ttf-mscorefonts-installer && sudo fc-cache -f
  displayName: 'Linux - install windows fonts'
  condition: eq(variables['friendlyPlatform'], 'Linux')
- task: Assembly-Info-NetCore@3
- task: DotNetCoreCLI@2
  displayName: 'dotnet build'
  inputs:
    command: 'build'
    projects: '$(Build.SourcesDirectory)/$(solutionName)'
    arguments: '--configuration $(buildConfiguration)'
- task: DotNetCoreCLI@2
  displayName: 'dotnet test - skipping EOLib.Graphics.Test (not supported on VSTS agent)'
  inputs:
    command: 'test'
    projects: '$(Build.SourcesDirectory)/$(solutionName)'
    arguments: '--filter "TestCategory!=GraphicsDevice" --configuration $(buildConfiguration)'
    testRunTitle: $(friendlyPlatform)

- task: ArchiveFiles@2
  displayName: 'ZIP EndlessClient'
  inputs:
    rootFolderOrFile: $(Build.SourcesDirectory)/bin/$(buildConfiguration)/client/$(dropDir)/
    archiveFile: $(Build.ArtifactStagingDirectory)/EndlessClient.$(friendlyPlatform).zip
- task: ArchiveFiles@2
  displayName: 'ZIP EOBot'
  inputs:
    rootFolderOrFile: $(Build.SourcesDirectory)/bin/$(buildConfiguration)/utils/EOBot/net6.0/
    archiveFile: $(Build.ArtifactStagingDirectory)/EOBot.$(friendlyPlatform).zip

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifacts'
  inputs:
    PathtoPublish: $(Build.ArtifactStagingDirectory)
    ArtifactName: EndlessClient

- script: |
    git tag build/$(Build.BuildNumber)
    git push origin build/$(Build.BuildNumber)
  workingDirectory:  $(Build.SourcesDirectory)
  displayName: Tag sources on CI/Manual builds
  condition: and(succeeded(), or(eq(variables['build.reason'], 'IndividualCI'), eq(variables['build.reason'], 'Manual')))
